<a href="https://colab.research.google.com/github/ugurguven99/IntroMachineLearning/blob/main/IntroMachineLearningWeek2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

#numpys bacis examples

#creating array
array1=np.array([1,2,3])
print(array1)

array3=np.array([1,2,3,4])

print(array3[3])

arr=np.array([1,2,3,4,5,6])
print(arr[3]+arr[5])

#2d arrays

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,2])


#array slicing

arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])


print(arr)
print('shape of array :', arr.shape)


#pandas basic
import pandas

mydataset={
  'arabalar':["Mazda","Toyota","Mercedes","Audi","Opel","Renault"],
  'yaş': [3,7,2,4,7,1],
  'renk':["mavi","kırmızı","siyah","metalik gri","yeşil","siyah"],
  'motor hacmi':["1.6","3","1.5","1.5","1.6","2"]
}
myvar=pandas.DataFrame(mydataset)
print(myvar)


[1 2 3]
4
10
3
[2 3 4 5]
[[2 3 4]
 [7 8 9]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape of array : (2, 5)
   arabalar  yaş         renk motor hacmi
0     Mazda    3         mavi         1.6
1    Toyota    7      kırmızı           3
2  Mercedes    2        siyah         1.5
3      Audi    4  metalik gri         1.5
4      Opel    7        yeşil         1.6
5   Renault    1        siyah           2
